### ISSUE TITLE
Ejs-autocomplete doesn't work after 16.1.42

### ISSUE THREAD

**Issue by LastCodeDE** [syncfusion/ej2-ng-dropdowns#7] opened 2018-06-01 12:41 UTC
Hello,

we have, after the update to 16.1.42 a new issue with our autocomplete.

When we press a key, the input field will be replaced with an empty string. So we can not insert any text.

We need a very IMPORTANT fix for this. When we downgrade to 16.1.32 the autocomplete works, but the dropdownlist does not. In opposite to 16.1.42 the dropdownlist works but the autocomplete does not.

Regards

**Comment by PrinceOliver** [comment] 2018-06-05 13:30
Hi LastCodeDE,

Thank you for your update,

We have checked the issue, reported by you. The filtering in AutoComplete works fine on our end. 

We have attached a test sample for your reference, kindly refer to the following link: https://stackblitz.com/edit/angular-zfv5kk 

Kindly check the above sample and let us know if we have missed any steps to replicate the issue in our end. We suspect that the issue may arise based on the following reasons.
1.    You might have handled the change event to process the input text in your application end.
2.    The value property might be null on each key press through two-way binding. (We ensured this scenario, but we couldn’t reproduce the issue in our end).

Additional information would greatly help us in replicating the issue and locating the cause of the issue. If possible, kindly share following information.
1.    Packages.Json file
2.    Screenshot or video demonstration of the issue   
3.    Code snippet

This will be help us provide a better solution.

Regards,
Prince

**Comment by LastCodeDE** [comment] 2018-06-06 07:55
Hay @PrinceOliver ,

I used your link and reproduced the failure:
https://stackblitz.com/edit/angular-kwbmdj

The failure happens when we change the datasource.

Regards
LastCodeDE

**Comment by PrinceOliver** [comment] 2018-06-11 05:51
Hi LastCodeDE,

Thank you for your update.

We could replicate the issue in our end. We will consider it as a defect and work towards resolving this issue. The fix will be included in the upcoming volume 2 release. We appreciate your patience until then.

Meanwhile, from the sample you shared, we could see that you are trying to prevent the filtering request for word less than 3 characters. If this is your requirement, it can be achieved using minLength property. 

For more information refer to the following documentation link: https://ej2.syncfusion.com/16.1.37/angular/documentation/auto-complete/filtering.html#limit-the-minimum-filter-character

Regards,
Prince

**Comment by PrinceOliver** [comment] 2018-07-06 15:46
Hi @LastCodeDE,

Thanks for your  patience.         
     
We have fixed the reported issue  and rolled out in  v16.1.42 release. Now, you can upgrade the  npm package to this version on your application.         
        
Please let us know, if you have any other concern, we will be happy to assist you.         
     
Regards,
Prince

**Closed** 2018-10-30 15:09 UTC
