### ISSUE TITLE
When change datasource at runtime ngModel doesn't work.

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-dropdowns#6] opened 2018-05-08 12:50 UTC
Version: 16.1.32

When we change the datasource at runtime and set the value over ngModel in a custom control it doesn't work. In the set value routine you get only "set value equal null".

So we can't work with the dropdown, because we must change the datasource for a new filter. We can't also find realstic examples. All examples doen't really work with the ngModel. In Angular is the use of ngModel important for classes.

Regards
j.nord

**Comment by LastCodeDE** [comment] 2018-05-08 14:43
We are using version 16.1.32 too.

The same problem happens here too. To set ngModel doesn't work. 
We have so many problems with ej2-ng-dropdownlist. Using a basic html select-box was so much easier.

Regards

**Comment by saravanangn** [comment] 2018-05-10 05:49
Hi @j-nord  / @LastCodeDE ,

Sorry for the inconvenience.
We have analyzed your query and can reproduce the reported issue. When we are changing the data source at runtime, we reset the value to default. Since we are not aware of new data source, the ngModel value does not update to the component. 
We will consider this as a bug and logged a report for the same. The fix for the issue will be available on May 15, 2018 release. Meanwhile, we will add the realistic demo for ngModel in sample browser for our component.

@LastCodeDE  - Could you please share the difficulties that you faced while using the DropDownList? It will be helpful to resolve the issues earlier. 

Regards,
Saravanan G

**Comment by LastCodeDE** [comment] 2018-05-11 05:00
I hope after the fix the issue will be solved.

@saravanangn 
When I update this module, new issues which were not there before happen. I would prefer that in future on the documentation, there is an example for ngModel too.

How can an issue like this one happen? I think the updates will be released before they are sufficiently tested.

Regards
LastCodeDE

**Comment by saravanangn** [comment] 2018-05-14 05:14
Hi, @LastCodeDE,

Already we have considered to improve the Angular documentation and Angular sample browser samples with “ngModel” in our components. we assure you that we will do our best in future to ensure our components with all functionalities before release.

Regards,
Saravanan G

**Comment by saravanangn** [comment] 2018-05-16 04:00
@j-nord  / @LastCodeDE ,

We have fixed the reported issue and rolled out in  **v16.1.42** release. Now, you can upgrade the npm package to this version on your application.         

https://www.npmjs.com/package/@syncfusion/ej2-ng-dropdowns

Please let us know, if you have any other concern, we will be happy to assist you.

Regards,
Saravanan G

**Comment by LastCodeDE** [comment] 2018-06-01 12:36
Nice fix. The dropdownlists works great.

**Unfortuntately our auto-complete-box doesn't work anymore.**

I can not see that the changes was tested.

**Comment by rajendranr-5483** [comment] 2018-07-05 09:53
@LastCodeDE , we have follow-up further queries on this thread.

https://github.com/syncfusion/ej2-ng-dropdowns/issues/7

Regards,
Rajendran R

**Closed** 2018-07-05 11:20 UTC
